server {
    listen 80 default_server;
    listen 443 default_server;

    server_name social-network;

    location /static/ {
        alias /app/src/static/;
    }

    location /media/ {
        alias /app/src/media/;
    }

    # Proxy pass requests to backend and enable WebSocket support
    location / {
        proxy_pass http://backend:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}